[default]
DEBUG = false
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.db'
SECRET_KEY = "jadkfbsdkjbfbh"
PASSWORD_SCHEMES = ['pbkdf2_sha512', 'md5_crypt']
EXTENSIONS = [
    # "src.extensions.database:init_app",
    "src.extensions.blueprints:init_app",
    "src.extensions.database:init_app",
    "src.extensions.commands:init_app"
]


[development]
EXTENSIONS = [
    "dynaconf_merge_unique"  # to reuse extensions list from [default]
]
DEBUG = true


[production]
SQLALCHEMY_DATABASE_URI = 'sqlite:///production.db'